---
kind: pipeline
type: kubernetes
name: publish-backend

steps:
  - name: publish
    image: plugins/docker
    settings:
      context: backend
      dockerfile: backend/Dockerfile
      registry: ghcr.io
      repo: ghcr.io/thecodinglab/guess-the-output/backend
      tags: latest
      username:
        from_secret: github_username
      password:
        from_secret: github_token

trigger:
  branch:
  - main

---
kind: pipeline
type: kubernetes
name: publish-frontend

steps:
  - name: publish
    image: plugins/docker
    settings:
      context: frontend
      dockerfile: frontend/Dockerfile
      registry: ghcr.io
      repo: ghcr.io/thecodinglab/guess-the-output/frontend
      tags: latest
      username:
        from_secret: github_username
      password:
        from_secret: github_token

trigger:
  branch:
  - main

---
kind: pipeline
type: ssh
name: deploy

server:
  host: 185.220.157.253
  user: ubuntu
  ssh_key:
    from_secret: deploy_key

steps:
  - name: deploy
    commands:
      - cd config
      - docker compose pull
      - docker compose up -d
    environment:
      HOME: /home/ubuntu

depends_on:
  - publish-backend
  - publish-frontend

trigger:
  branch:
  - main

---
kind: signature
hmac: 672f67f1066ff423039a7b5a62afe573d6fb64c0f3e63ca878c85e45c988558f

...
