---
kind: pipeline
type: kubernetes
name: publish-backend

steps:
  - name: publish
    image: plugins/docker
    settings:
      context: backend
      dockerfile: backend/Dockerfile
      registry: ghcr.io
      repo: ghcr.io/thecodinglab/guess-the-output/backend
      tags: latest
      username:
        from_secret: github_username
      password:
        from_secret: github_token

---
kind: pipeline
type: ssh
name: deploy

server:
  host: 185.220.157.253
  user: ubuntu
  ssh_key:
    from_secret: deploy_key

steps:
  - name: deploy
    commands:
      - id
      - pwd
      
      - cd config
      - docker compose pull
      - docker compose up -d

depends_on:
  - publish-backend

---
kind: signature
hmac: 907c6dbeae45d8a2c5ad396f0efa1fa5143a527910862406b16d7e67b02adeca

...
